export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const GYNECOLOGIST_PATH = 'GYNECOLOGIST_PATH';
export const FNDOCRINOLOGIST_PATH = 'FNDOCRINOLOGIST_PATH';
export const PATIENT_SELECT_CARD = 'PATIENT_SELECT_CARD';
export const QUESTION_INDEX = 'QUESTION_INDEX';
export const RESET_QUESTION_COUNTER = 'RESET_QUESTION_COUNTER';
